# https://dev.azure.com/home-assistant

trigger:
  batch: true
  tags:
    include:
    - '*'
pr: none
variables:
  - name: versionWheels
    value: '1.2-3.7-alpine3.10'
  - name: versionPython
    value: '3.7-alpine3.10'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:
- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderArch: ['amd64']
    wheelsPrebuildDir: 'tf_wheels'
    preBuild:
    - script: |
        set -e
        mkdir -p tf_wheels

        sudo docker build \
          --build-arg BUILD_FROM=homeassistant/$(buildArch)-base-python:$(versionPython) \
          --build-arg BUILD_ARCH=$(buildArch) \
          --tag tensorflow:$(buildArch) \
          .

        sudo docker run --rm -v "$(pwd)/tf_wheels:/tf_wheels" \
          tensorflow:$(buildArch) cp /usr/src/wheels/* /tf_wheels/
      displayName: 'Build wheels'
