# https://dev.azure.com/home-assistant

trigger:
  batch: true
  tags:
    include:
    - '*'
pr: none
variables:
  - name: versionWheels
    value: '1.13.0-3.8-alpine3.12'
  - name: versionPython
    value: '3.8-alpine3.12'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:
- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderArch: ['amd64']
    wheelsPrebuildDir: 'tf_wheels'
    preBuild:
    - script: |
        set -e

        container_id="tensorflow-$(buildArch)-$(Build.SourceBranchName)"
        mkdir -p tf_wheels

        docker build \
          --build-arg BUILD_FROM=homeassistant/$(buildArch)-base-python:$(versionPython) \
          --build-arg BUILD_ARCH=$(buildArch) \
          --tag tensorflow:$(buildArch) \
          .

        # Copy wheels out
        docker create --name "${container_id}"  \
          tensorflow:$(buildArch) \
            bash -c "sleep 90000"
        docker cp "${container_id}:/usr/src/wheels/." tf_wheels/

        docker stop "${container_id}"
        docker rm -f "${container_id}"
        docker rmi -f tensorflow:$(buildArch)
      displayName: 'Build wheels'
